settings:
  title: 'Status Page'
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 10 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: myorderboxhq # unique identifier
    name: APIs
    description: 'Backoffice/ Terminal and other systems using APIs' # default=empty
    url: 'https://go.myorderboxhq.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 302 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: gb-myfoodfast-co-uk
    name: Websites
    description: 'Frontend Websites for restuants'
    url: 'https://gb.myfoodfast.co.uk/'
    method: GET
    expectStatus: 200
    linkable: false